server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  # Zipkin
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      mvc:
        routes:
          - id : ORDER-SERVICE
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order/**
          - id: PAYMENT-SERVICE
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payment/**
          - id: PRODUCT-SERVICE
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/product/**
logging:
  pattern:
    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'
management:
  tracing:
    sampling:
      probability: 1.0

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}